# Generated by Django 4.1.4 on 2022-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
