# Generated by Django 4.1.5 on 2023-01-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sharedorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedorganization',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
