# Generated by Django 4.1.5 on 2023-01-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_invitedorganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedorganization',
            name='user',
        ),
        migrations.AddField(
            model_name='sharedorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
