# Generated by Django 4.1.5 on 2023-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_user_invitedorganization_invite_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedorganization',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sharedorganization',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
