# Generated by Django 4.1.5 on 2023-01-09 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_invitedorganization_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedorganization',
            name='invite_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_by_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedorganization',
            name='invite_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='viewer', max_length=15)),
                ('invite_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_organization', to=settings.AUTH_USER_MODEL)),
                ('invite_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
