# Generated by Django 4.1.5 on 2023-01-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitedorganization',
            old_name='invite_by',
            new_name='shared_by',
        ),
        migrations.RenameField(
            model_name='invitedorganization',
            old_name='invite_to',
            new_name='shared_to',
        ),
        migrations.RenameField(
            model_name='sharedorganization',
            old_name='invite_by',
            new_name='shared_by',
        ),
        migrations.RenameField(
            model_name='sharedorganization',
            old_name='invite_to',
            new_name='shared_to',
        ),
        migrations.RemoveField(
            model_name='organizationpermissions',
            name='invite_by',
        ),
        migrations.RemoveField(
            model_name='organizationpermissions',
            name='invite_to',
        ),
        migrations.AddField(
            model_name='organizationpermissions',
            name='shared_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='shared_from_organization', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationpermissions',
            name='shared_to',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_organization', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
