# Generated by Django 4.1.5 on 2023-01-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='profile',
            new_name='image',
        ),
    ]
