# Generated by Django 4.1.4 on 2022-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('code', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, choices=[('create', 'create'), ('forgot', 'forgot'), ('changenumber', 'changenumber')], max_length=100)),
                ('verification_token', models.CharField(max_length=200)),
                ('use', models.BooleanField(default=False)),
                ('role', models.CharField(default='buyer', max_length=100)),
                ('timeout', models.DateTimeField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
