# Generated by Django 4.1.4 on 2022-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='timeout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(blank=True, choices=[('create', 'create'), ('forgot', 'forgot'), ('changenumber', 'changenumber')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='use',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='verification_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
